from .usuario import Usuarios as UsuariosResources
from .usuario import Usuario as UsuarioResources
from .libro import Libros as LibrosResources
from .libro import Libro as LibroResources
from .Authentication import SignIn as SignInResources
from .Authentication import Login as LoginResources
from .prestamo import Prestamos as PrestamosResources
from .prestamo import Prestamo as PrestamoResources
from .notificacion import Notificaciones as NotificacionesResources
from .configuracion import Configuraciones as ConfiguracionesResources
from .reseña import Valoraciones as ValoracionesResources
from .reseña import Comentarios  as ComentariosResources