from .animal import Animal as AnimalModel
from .libro import Libro as LibroModel
from .notificacion import Notificacion as NotificacionModel
from .prestamo import Prestamo as PrestamoModel
from .reseña import Reseña as ReseñaModel
from .usuario import Usuario as UsuarioModel
from .configuracion import Configuracion as ConfiguracionModel
from .autor import Autor as AutorModel
from .historia_clinica import HistoriaClinica as HistoriaClinicaModel